version = 1
SPDX-PackageName = "oversight-certificate"
SPDX-PackageSupplier = "flxk1"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 flxk1"
SPDX-License-Identifier = "MIT"
